_prefs: 
  saveCenter: false
_properties: {}
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox</a> <a href='https://openstreetmap.org/about/' target='_blank'>&copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -82.9688
  - 16.8466
  - 4
description: ''
format: "png8:m=h:c=192"
interactivity_layer: ''
layers: null
maxzoom: 21
minzoom: 0
name: Pirates Return
source: "mapbox:///mapbox.mapbox-streets-v6"
styles: 
  - style.mss
  - labels.mss
  - illustrations.mss
template: ''
