_prefs: 
  saveCenter: true
_properties: {}
attribution: "<a href='http://mapbox.com/about/maps' target='_blank'>Terms & Feedback</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -41.1328125
  - 22.674847351188536
  - 3
description: ''
format: "png8:m=h"
interactivity_layer: ''
maxzoom: 21
minzoom: 0
mtime: 1379437640975
name: Pirates Return
scale: 1
source: "mapbox:///mapbox.mapbox-streets-v4"
styles: 
  - style.mss
  - labels.mss
  - illustrations.mss
template: ''
